### ISSUE TITLE
data_lag, management_lag parameters

### ISSUE THREAD

**Issue by AndyCampbell** [iagomosqueira/WKREBUILD_toolset#18]
How do the data_lag and management_lag parameters passed to mp() and mps() relate to the iy parameter? I'm attempting to run a simulation with zero lags by setting these parameters to zero (to compare with a previous exercise) but call to mp() raises 
Error in ix[, c(1, 3), ][is.na(ix[, c(1, 3), ])] <- iy[, c(1, 3), ][!is.na(iy[,  : 
  replacement has length zero (data_lag=0)
or
Error in x@.Data[i, j, k, l, m, n] <- value : 
  number of items to replace is not a multiple of replacement length (managment_lag=0)

**Comment by iagomosqueira** [comment]
The error comes from something that should, and will be fixed. But the issue is also what no management lag means. If our current year is 2021, and we make a decision for 2021, then there is nothing happening in 2022, and when 2022 comes we haven't projected the OM for that year. I suppose this scenario works only if we project to the start of 2022 the survivors of 2021, plus recruitment.

We can add that, but I am still uncertain it makes sense. If it does not, then we should ensure management_lag > 0.

**Comment by iagomosqueira** [comment]
Are you aiming at running it with the STF in tac.is? Then that would need to be told to run a forecast for the current year.

**Comment by AndyCampbell** [comment]
Thanks for your thoughts and feedback here. My motivation to compress the time scale (i.e. remove lags) was to mimic the simulations from 2020 but, as you say, it's not a particularly useful exercise in itself as it's probably not very realistic. Perhaps scenarios will arise where a shorter time scale could be relevant but until then, probably best to leave the toolset as it is, with the exception of informing users when they try to use an inappropriate lag. Cheers
